### ISSUE TITLE
Write output to workspace directory

### ISSUE THREAD

**Issue by joshzarrabi** [paketo-buildpacks/dotnet-publish#132]
## Current situation

This buildpack builds a `.Net` app from source code using the `dotnet publish` command. It writes executable to the `layers` directory and then writes the location of the executable to the `PUBLISH_OUTPUT_LOCATION` env variable at build time so the `dotnet execute` buildpack will know where to run the app from. 

## Why this needs to change

This is a problem because it tightly couples this buildpack to any other downstream buildpack that would want to consume its output.  Any consumer buildpack would need to both know about the environment variable and be able to use it at `build` time. 

We attempted to have the `Procfile` buildpack consume the output of this buildpack to allow users to write their own start command, and found that it was impossible because the `Procfile` buildpack doesn't even run at `build` time, so it would have no way of consumer the environment variable. 

Furthermore, every other buildpack runs the app from the `workspace` directory, so this breaks that pattern.

## Proposed Solution

We should:.
1. Build the executable into some temporary directory.
2. Clear the workspace directory of the source code.
3. Place the executable and  `csproj` file in the workspace directory. 

We need to clear the workspace directory because otherwise the app executable will conflict with the source code directory, as documented here: https://github.com/paketo-buildpacks/dotnet-publish/issues/87

**Comment by fg-j** [comment]
@paketo-buildpacks/dotnet-core-maintainers I'm not sure why the `*.csproj` file would need to be left in the `workspace` directory after the build phase. Any thoughts on this? As far as I can tell, the [`dotnet-publish`](https://github.com/paketo-buildpacks/dotnet-publish/blob/581572afad993a8b17bc6f83157c1f64f44b5f6e/detect.go#L36) and [`dotnet-execute`](https://github.com/paketo-buildpacks/dotnet-execute/blob/c81ab77e8700650e8cfad5754ce7e1a64fc71bee/detect.go#L93) buildpacks only care about the proj file during detection.
