### ISSUE TITLE
Why is there a self-contained test?

### ISSUE THREAD

**Issue by thitch97** [paketo-buildpacks/dotnet-publish#141]
The buildpack contains a test which seems to validate [building a self-contained app](https://github.com/paketo-buildpacks/dotnet-publish/blob/main/integration/self_contained_test.go). Does this test actually need to be included in this buildpack? If so, is the app source for that test set up correctly? The source layout [at this previous commit](https://github.com/paketo-buildpacks/dotnet-publish/tree/bbf9467038a9e0edd653cd629c179dbdab1a7782/integration/testdata/self_contained_msbuild) does not contain the output of `dotnet publish` whereas the most recent ones do (e.g. [this commit](https://github.com/paketo-buildpacks/dotnet-publish/tree/79650c83f6d056cb6937997cfd54b27defa84e52/integration/testdata/self_contained_msbuild)). What is the intention of this test and the subsequent correct configuration of the test app?

**Comment by fg-j** [comment]
Mystery solved. tl;dr: The dotnet-publish buildpack is _not_ building our "self-contained" app as a self-contained executable. We should probably get rid of this misleading fixture. We can add one that actually *needs* to be self-contained to build properly once #145 is resolved.

The so-called `self_contained_test` doesn't seem to be testing that the buildpack can build source code into a self-contained app. The test [only asserts that the provided fixture builds](https://github.com/paketo-buildpacks/dotnet-publish/blob/main/integration/self_contained_test.go#L67-L86). 

I experimented with the fixture and the 2.1 version of the dotnet SDK, which is the [version used in that fixture](https://github.com/paketo-buildpacks/dotnet-publish/blob/1445a98cf17882dc4a0ca768c9c3d76cc0385826/integration/testdata/self_contained_msbuild/msbuild_self_contained.csproj#L4).

I used the .NET 2.1 docker image published by Microsoft 
```
cd ~/workspace/paketo-buildpacks/dotnet-publish/integration/testdata/self_contained_msbuild
docker run -it -v "$(pwd)":/workspace mcr.microsoft.com/dotnet/sdk:2.1
```

and experimented with running different `dotnet publish` commands on the app.

First, I tried the [command that the buildpack currently runs](https://github.com/paketo-buildpacks/dotnet-publish/blob/main/dotnet_publish_process.go#L35-L41).
```
dotnet publish /workspace --configuration Release --runtime ubuntu.18.04-x64 --self-contained false --output /tmp/self-contained-false
```
This results in 35 generated files:
```
ls -al /tmp/self-contained-false/ | wc -l
35
```
---
Then, I switched to `--self-contained=true`

```
dotnet publish /workspace --configuration Release --runtime ubuntu.18.04-x64 --self-contained true --output /tmp/self-contained-true
```

This results in 215 generated files:
```
 ls -al /tmp/self-contained-true/ | wc -l
215
```

So it's safe to say that the command the buildpack is currently running is _not_ building our "self-contained" app as a self-contained executable. We should probably get rid of this misleading fixture. We can add one that actually *needs* to be self-contained to build properly once #145 is resolved.
