### ISSUE TITLE
Restructure: Rename to dotnet-publish and rewrite for packit

### ISSUE THREAD

**Issue by joshzarrabi** [paketo-buildpacks/dotnet-publish#84]
### Background

The buildpack builds `dll` files with the `dotnet publish` command that are  executed by the `dotnet-core-conf` buildpack. 

### Proposal

In order to conform the the [restructure rfc](https://github.com/paketo-buildpacks/dotnet-core/blob/main/rfcs/0001-restructure.md), this buildpack should

* Be rewritten to be `packit` compliant
* Be renamed to `dotnet-publish` as that is a more descriptive name. 

For now we should keep all functionality the same.

### Note:

Make sure to go through the rest of the README's in the language family and change the references to theis buildpack to be correct.

**Comment by ForestEckhardt** [comment]
The implementation for this buildpack is done as PR #88. There still needs to be an update to the README

**Comment by ForestEckhardt** [comment]
PR #91 fixes the README
