### ISSUE TITLE
Is the logic to check if Aspnet should be included missing checking of ".App" & ".All"?

### ISSUE THREAD

**Issue by arjun024** [paketo-buildpacks/dotnet-publish#98]
See [before](https://github.com/paketo-buildpacks/dotnet-publish/blob/v0.0.119/cmd/detect/main.go#L155-L168) and after packit [rewrite](https://github.com/paketo-buildpacks/dotnet-publish/blob/v0.0.121/dotnet_project_file_parser.go#L51-L68). It seems like the new logic doesn't check for `Microsoft.AspNetCore.App` and `Microsoft.AspNetCore.All`. It seems to assume `Microsoft.NET.Sdk.Web` as sdk suffices the criterion. Could you investigate?

**Comment by fg-j** [comment]
According to [this Microsoft documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1079), 

> The Microsoft.AspNetCore.All package is not supported when targeting .NET Core 3.0 or higher.

If we want to properly support .NET Core 2.0 apps, we should check for the `Microsoft.AspNetCore.All` package in the projfile.

**Comment by fg-j** [comment]
Update: this issue has since been resolved: See [the updated ASPNetIsRequired function](https://github.com/paketo-buildpacks/dotnet-publish/blob/main/dotnet_project_file_parser.go#L42-L76).
